apiVersion: v1
kind: Pod
metadata:
  name: multi-container-1
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: container-1
      image: nginx
    - name: container-2
      image: ubuntu
      args:
        - "sleep"
        - "3600"