apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    dept: dept-1
    team: team-1
spec:
  containers:
    - name: nginx-1
      image: nginx

# for query on pods with specific labels
# sudo kubectl get pod -l dept=dept-1,team=team-1

