apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    dept: dept-2
    team: team-2
spec:
  containers:
    - name: nginx-2
      image: nginx


# for query on pods with specific labels
# sudo kubectl get pod -l dept=dept-1,team=team-1
