apiVersion: v1
kind: Pod
metadata:
  name: second-pod
  labels:
    app: nginx-app2
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

# this pod is for configuring the replicaset for this predefined pod
# the replicaset for this pod is existing-pods-with-replica.yml