apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
spec:
  selector:
    matchLabels:
      app: second-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: second-deployment
    spec:
      containers:
        - name: nginx-for-second-deployment
          image: nginx
          ports:
            - containerPort: 80



# if you create a deployment and after creating it you change the configuration , kubernetes will create
# another replicaset for your purpose